export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 bg-white dark:bg-slate-900 p-8 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300">
      <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100">Privacy Policy</h1>
      
      <div className="space-y-4">
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mt-6">1. Data Collection & Storage</h2>
        <p>
          EasyInvoice is a client-side application. We do not transmit your invoice data, business details, or client information to any external servers. All data you enter into the application remains securely stored within your browser's local storage (`localStorage`).
        </p>

        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mt-6">2. Use of Generated PDFs</h2>
        <p>
          The PDF documents generated by this tool are created entirely within your browser using client-side libraries. No copies of your generated invoices are sent to or stored on our servers.
        </p>

        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mt-6">3. Third-Party Analytics</h2>
        <p>
          We do not use tracking cookies or third-party analytics to monitor your use of the invoice generation features.
        </p>

        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mt-6">4. Contact Us</h2>
        <p>
          If you have questions or concerns about this Privacy Policy, please reach out via GitHub.
        </p>
      </div>
    </div>
  )
}
